name: Test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
          cache: true
      - name: Install dependencies
        run: |
            pdm install
            pdm install -G dev
      - name: Run tests
        run: |
            if [ -d tests/ ]; then
                pdm run pytest
            else
                echo "No tests/ directory found, skipping"
            fi
